/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/gt3rs/scene-opt.glb --shadows --types 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { JSX } from 'react'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Disc_FL: THREE.Mesh
    Hub_FL: THREE.Mesh
    Rim_Center_FL: THREE.Mesh
    Rim_Outer_FL: THREE.Mesh
    Tire_FL: THREE.Mesh
    Brake_Static_FL_1: THREE.Mesh
    Brake_Static_FL_2: THREE.Mesh
    Caliper_Paint_FL: THREE.Mesh
    Disc_FR: THREE.Mesh
    Hub_FR: THREE.Mesh
    Rim_Center_FR: THREE.Mesh
    Rim_Outer_FR: THREE.Mesh
    Tire_FR: THREE.Mesh
    Brake_Static_FR_1: THREE.Mesh
    Brake_Static_FR_2: THREE.Mesh
    Caliper_Paint_FR: THREE.Mesh
    Disc_RL: THREE.Mesh
    Hub_RL: THREE.Mesh
    Rim_Center_RL: THREE.Mesh
    Rim_Outer_RL: THREE.Mesh
    Tire_RL: THREE.Mesh
    Brake_Static_RL_1: THREE.Mesh
    Brake_Static_RL_2: THREE.Mesh
    Caliper_Paint_RL: THREE.Mesh
    Disc_RR: THREE.Mesh
    Hub_RR: THREE.Mesh
    Rim_Center_RR: THREE.Mesh
    Rim_Outer_RR: THREE.Mesh
    Tire_RR: THREE.Mesh
    Brake_Static_RR_1: THREE.Mesh
    Brake_Static_RR_2: THREE.Mesh
    Caliper_Paint_RR: THREE.Mesh
    Door_Accent_L: THREE.Mesh
    Door_Glass_L: THREE.Mesh
    Door_Interior_Base_L_1: THREE.Mesh
    Door_Interior_Base_L_2: THREE.Mesh
    Door_Interior_Base_L_3: THREE.Mesh
    Door_Leather_Primary_L: THREE.Mesh
    Door_Leather_Secondary_L: THREE.Mesh
    Door_Metal_Trim_L_1: THREE.Mesh
    Door_Metal_Trim_L_2: THREE.Mesh
    Door_Metal_Trim_L_3: THREE.Mesh
    Door_Mirror_L: THREE.Mesh
    Door_Paint_L: THREE.Mesh
    Door_Painted_Trim_L_Dynamic: THREE.Mesh
    Door_Plastic_L_1: THREE.Mesh
    Door_Plastic_L_2: THREE.Mesh
    Door_Plastic_L_3: THREE.Mesh
    Door_Accent_R: THREE.Mesh
    Door_Glass_R: THREE.Mesh
    Door_Interior_Base_R_1: THREE.Mesh
    Door_Interior_Base_R_2: THREE.Mesh
    Door_Interior_Base_R_3: THREE.Mesh
    Door_Leather_Primary_R: THREE.Mesh
    Door_Leather_Secondary_R: THREE.Mesh
    Door_Metal_Trim_R_1: THREE.Mesh
    Door_Metal_Trim_R_2: THREE.Mesh
    Door_Mirror_R: THREE.Mesh
    Door_Paint_R: THREE.Mesh
    Door_Painted_Trim_R_Dynamic: THREE.Mesh
    Door_Plastic_R_1: THREE.Mesh
    Door_Plastic_R_2: THREE.Mesh
    Door_Plastic_R_3: THREE.Mesh
    Hood_Aero_Vents_Static: THREE.Mesh
    Hood_Badge_Logo: THREE.Mesh
    Hood_Carbon_Center: THREE.Mesh
    Hood_Paint: THREE.Mesh
    Hood_Radiator_Static: THREE.Mesh
    Headlight_Emissive: THREE.Mesh
    HeadLight_Glass: THREE.Mesh
    HeadLight_Housing_Static: THREE.Mesh
    Signal_Front_Emissive: THREE.Mesh
    Signal_Front_Glass: THREE.Mesh
    Signal_Side_Emissive: THREE.Mesh
    Signal_Side_Glass: THREE.Mesh
    Licence_Plate_Emissive: THREE.Mesh
    License_Plate_Glass: THREE.Mesh
    Rear_Reflactors_Red: THREE.Mesh
    Tailgate_Brake_Emissive: THREE.Mesh
    Tailgate_Glass: THREE.Mesh
    Taillight_Brake_Emissive: THREE.Mesh
    Taillight_Housing_Static_AntiChrome: THREE.Mesh
    Taillight_Housing_Static_PlasticSmooth: THREE.Mesh
    Taillight_Main_Glass: THREE.Mesh
    Taillight_Strip_Emissive: THREE.Mesh
    Wing_Flap_Active: THREE.Mesh
    Aero_Engine_Fans_Carbon: THREE.Mesh
    Aero_Fender_Louvers: THREE.Mesh
    Aero_Front_Splitter: THREE.Mesh
    Aero_Rear_Diffuser: THREE.Mesh
    Aero_Roof_Panel: THREE.Mesh
    Aero_Roof_Rails: THREE.Mesh
    Aero_Sideskirts: THREE.Mesh
    Aero_Tailgate: THREE.Mesh
    Aero_Wing_Supports: THREE.Mesh
    Badge_Rear_Lettering: THREE.Mesh
    Chassis_Paint: THREE.Mesh
    Chassis_Underbody_Static_1: THREE.Mesh
    Chassis_Underbody_Static_2: THREE.Mesh
    Chassis_Underbody_Static_3: THREE.Mesh
    Chassis_Window_Trims_Static_1: THREE.Mesh
    Chassis_Window_Trims_Static_2: THREE.Mesh
    Chassis_Window_Trims_Static_3: THREE.Mesh
    Chassis_Window_Trims_Static_4: THREE.Mesh
    Exterior_Badges_1: THREE.Mesh
    Exterior_Badges_2: THREE.Mesh
    Exterior_Badges_3: THREE.Mesh
    Windows_Cabin_Static: THREE.Mesh
    Wing_Endplates: THREE.Mesh
    Interior_SteeringWheel_Buttons_Static_1: THREE.Mesh
    Interior_SteeringWheel_Buttons_Static_2: THREE.Mesh
    Interior_SteeringWheel_Buttons_Static_3: THREE.Mesh
    Interior_SteeringWheel_Grip: THREE.Mesh
    Interior_SteeringWheel_Stitching_Dynamic: THREE.Mesh
    Interior_SteeringWheel_Trim_Dynamic: THREE.Mesh
    Interior_Carbon_Trims_1: THREE.Mesh
    Interior_Carbon_Trims_2: THREE.Mesh
    Interior_Carpet_Static_1: THREE.Mesh
    Interior_Carpet_Static_2: THREE.Mesh
    Interior_Clock_Dial_Dynamic: THREE.Mesh
    Interior_Dash_Lower_Primary: THREE.Mesh
    Interior_Dash_Trim_Dynamic_1: THREE.Mesh
    Interior_Dash_Trim_Dynamic_2: THREE.Mesh
    Interior_Dash_Upper_Secondary: THREE.Mesh
    Interior_Glass_Static_1: THREE.Mesh
    Interior_Glass_Static_2: THREE.Mesh
    Interior_Glass_Static_3: THREE.Mesh
    Interior_Headliner: THREE.Mesh
    Interior_Metal_Accents_1: THREE.Mesh
    Interior_Metal_Accents_2: THREE.Mesh
    Interior_Metal_Accents_3: THREE.Mesh
    Interior_Mirror_Housing_Dynamic: THREE.Mesh
    Interior_Painted_Trims_Dynamic: THREE.Mesh
    Interior_Pedals_Metal: THREE.Mesh
    Interior_Pedals_Rubber: THREE.Mesh
    Interior_Screens_Digital_1: THREE.Mesh
    Interior_Screens_Digital_2: THREE.Mesh
    Interior_Seatbelts_Dynamic: THREE.Mesh
    Interior_Shifter_Base_Static_1: THREE.Mesh
    Interior_Shifter_Base_Static_2: THREE.Mesh
    Interior_Shifter_Trim_Dynamic: THREE.Mesh
    Interior_Shifter_Upholstery: THREE.Mesh
    Interior_SteeringColumn_Stalks_1: THREE.Mesh
    Interior_SteeringColumn_Stalks_2: THREE.Mesh
    Interior_SteeringColumn_Stalks_3: THREE.Mesh
    Interior_Stitching_Dynamic: THREE.Mesh
    Interior_Tacho_Dial_Dynamic: THREE.Mesh
    Interior_Tacho_Needle: THREE.Mesh
    Interior_Tub_Static_1: THREE.Mesh
    Interior_Tub_Static_2: THREE.Mesh
    Interior_Tub_Static_3: THREE.Mesh
    Interior_Tub_Static_4: THREE.Mesh
    Interior_Tub_Static_5: THREE.Mesh
    Interior_Tub_Static_6: THREE.Mesh
    Interior_Tub_Static_7: THREE.Mesh
    Interior_Tub_Static_8: THREE.Mesh
    Seats_Leather_Primary: THREE.Mesh
    Seats_Leather_Secondary: THREE.Mesh
    Seats_Metal_Mechanics: THREE.Mesh
    Seats_Metal_Mechanics_1: THREE.Mesh
    Seats_Metal_Mechanics_2: THREE.Mesh
    Seats_Metal_Mechanics_3: THREE.Mesh
    Seats_Metal_Mechanics_4: THREE.Mesh
    Seats_Metal_Mechanics_5: THREE.Mesh
    Chassis_Powertrain_Static_1: THREE.Mesh
    Chassis_Powertrain_Static_2: THREE.Mesh
    Exterior_ExhaustTips_Dynamic: THREE.Mesh
    Chassis_Suspension_Static: THREE.Mesh
  }
  materials: {
    Material_Disc_Static: THREE.MeshStandardMaterial
    Material_Structure_Lucid_Static: THREE.MeshStandardMaterial
    Material_Rim_Centerlock: THREE.MeshStandardMaterial
    Material_Rim_Primary: THREE.MeshStandardMaterial
    Material_Tire_Static: THREE.MeshStandardMaterial
    Material_Wheels_Bolts_Static: THREE.MeshStandardMaterial
    Material_Radiator_Static: THREE.MeshStandardMaterial
    Material_Caliper_Dynamic: THREE.MeshStandardMaterial
    Material_Interior_Stitching_Dynamic: THREE.MeshStandardMaterial
    Material_Glass_Cabin_Static: THREE.MeshPhysicalMaterial
    Material_Interior_LightGrey_Plastic_Static: THREE.MeshStandardMaterial
    Material_Front_Speaker_Static: THREE.MeshStandardMaterial
    Material_Exterior_Badges_Dynamic: THREE.MeshStandardMaterial
    Material_Leather_Primary: THREE.MeshStandardMaterial
    Material_Upper_Leather_Dynamic: THREE.MeshStandardMaterial
    Material_Interior_Metal_Static: THREE.MeshStandardMaterial
    Material_Interior_Metal_Lucid_Static: THREE.MeshStandardMaterial
    Material_Mirror_Glass_Static: THREE.MeshStandardMaterial
    Material_Chassis_Paint: THREE.MeshPhysicalMaterial
    Material_RubberTrim_Static: THREE.MeshStandardMaterial
    Material_Carbon_Trim_Static: THREE.MeshPhysicalMaterial
    Material_Exterior_LowerAero_Dynamic: THREE.MeshPhysicalMaterial
    Exterior_Badges: THREE.MeshStandardMaterial
    Material_Exterior_Weissach_Dynamic: THREE.MeshPhysicalMaterial
    Material_Headlight_Emissive: THREE.MeshStandardMaterial
    Material_Glass_Lights_Static: THREE.MeshPhysicalMaterial
    Material_Plastic_Smooth_Static: THREE.MeshStandardMaterial
    Material_Signal_Emissive: THREE.MeshStandardMaterial
    Material_LicensePlateLight_Emissive: THREE.MeshStandardMaterial
    Material_Reflector_Red_Static: THREE.MeshStandardMaterial
    Material_Taillight_Brake_Emissive: THREE.MeshStandardMaterial
    Material_Taillight_Housing_Static: THREE.MeshStandardMaterial
    Material_Taillight_Emissive: THREE.MeshStandardMaterial
    Material_Structure_Opaque_Static: THREE.MeshStandardMaterial
    Material_RubberTrim2_Staitc: THREE.MeshStandardMaterial
    Material_Glass_Black_Static: THREE.MeshStandardMaterial
    Material_Exterior_ExhaustTips_Dynamic: THREE.MeshStandardMaterial
    Material_SteeringWheel_Icons_Static: THREE.MeshStandardMaterial
    Material_SteeringWheel_Buttons_Static: THREE.MeshStandardMaterial
    Material_Logo_Static: THREE.MeshStandardMaterial
    Material_Wheel_Leather_Dynamic: THREE.MeshStandardMaterial
    Material_Interior_Plastic_Static: THREE.MeshStandardMaterial
    Material_Carbon_Trim_Lighter_Static: THREE.MeshPhysicalMaterial
    Material_Interior_Structure_Static: THREE.MeshStandardMaterial
    Material_Interior_Carpet_Static: THREE.MeshStandardMaterial
    Material_DashClock_Dynamic: THREE.MeshStandardMaterial
    Material_Interior_Plastic_Darker_Static: THREE.MeshStandardMaterial
    Material_Interior_Headliner_Static: THREE.MeshStandardMaterial
    Material_Interior_Clock_Static: THREE.MeshStandardMaterial
    Material_Interior_Vent_Static: THREE.MeshStandardMaterial
    Material_Interior_Accent_Dynamic: THREE.MeshStandardMaterial
    Material_Interior_Padel_Metal_Static: THREE.MeshStandardMaterial
    Material_Interior_Metal_Black_Lucid_Static: THREE.MeshStandardMaterial
    Material_Interior_Screen_Digital: THREE.MeshStandardMaterial
    Material_Interior_Screen_GPS_Digital: THREE.MeshStandardMaterial
    Material_SeatBelt_Dynamic: THREE.MeshStandardMaterial
    Material_Sticker_Tacho_Dynamic: THREE.MeshStandardMaterial
    Material_Interior_Plastic_Lucid_Static: THREE.MeshStandardMaterial
    Material_Warning_Triangle_Static: THREE.MeshStandardMaterial
    Material_Speakers_Static: THREE.MeshStandardMaterial
    Material_Behind_Vents_Static: THREE.MeshStandardMaterial
    Material_Interior_Metallic_Structure_Static: THREE.MeshStandardMaterial
    Material_Leather_Secondary: THREE.MeshStandardMaterial
    Material_Slide_Seat_Static: THREE.MeshStandardMaterial
    Material_SeatBelt_Buckle_Static: THREE.MeshStandardMaterial
    Material_SeatBelt_Release_Button_Static: THREE.MeshStandardMaterial
    Material_Buckle_Housing_Static: THREE.MeshStandardMaterial
    Material_Seat_Plastic_Static: THREE.MeshStandardMaterial
  }
}

export default function Gt3rsModel({ url, ...props }: JSX.IntrinsicElements['group'] & { url: string }) {
  const { nodes, materials } = useGLTF(url) as unknown as GLTFResult as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-0.773, 0.303, 1.163]}>
        <group position={[-0.007, 0.003, 0.011]}>
          <mesh castShadow receiveShadow geometry={nodes.Disc_FL.geometry} material={materials.Material_Disc_Static} position={[-0.013, -0.001, -0.16]} rotation={[-Math.PI / 2, -0.035, Math.PI]} scale={[-1.254, -1.076, -1.076]} />
          <mesh castShadow receiveShadow geometry={nodes.Hub_FL.geometry} material={materials.Material_Structure_Lucid_Static} position={[0.78, -0.003, -0.034]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh castShadow receiveShadow geometry={nodes.Rim_Center_FL.geometry} material={materials.Material_Rim_Centerlock} position={[-0.122, -0.008, -0.011]} rotation={[Math.PI / 2, 0, 0]} scale={-1.208} />
          <mesh castShadow receiveShadow geometry={nodes.Rim_Outer_FL.geometry} material={materials.Material_Rim_Primary} position={[-0.122, -0.008, -0.011]} rotation={[Math.PI / 2, 0, 0]} scale={-1.208} />
          <mesh castShadow receiveShadow geometry={nodes.Tire_FL.geometry} material={materials.Material_Tire_Static} position={[0.01, -0.001, -0.005]} rotation={[Math.PI / 2, 0, 0]} scale={[-1.414, -1.161, -1.161]} />
        </group>
        <group position={[-0.02, 0.001, -0.149]} rotation={[-Math.PI / 2, -0.035, Math.PI]} scale={[-1.254, -1.076, -1.076]}>
          <mesh castShadow receiveShadow geometry={nodes.Brake_Static_FL_1.geometry} material={materials.Material_Wheels_Bolts_Static} />
          <mesh castShadow receiveShadow geometry={nodes.Brake_Static_FL_2.geometry} material={materials.Material_Radiator_Static} />
        </group>
        <mesh castShadow receiveShadow geometry={nodes.Caliper_Paint_FL.geometry} material={materials.Material_Caliper_Dynamic} position={[-0.02, 0.001, -0.149]} rotation={[-Math.PI / 2, -0.035, Math.PI]} scale={[-1.254, -1.076, -1.076]} />
      </group>
      <group position={[0.773, 0.317, 1.168]}>
        <group position={[0.009, -0.019, 0.007]} rotation={[-Math.PI / 2, 0, 0]} scale={1.208}>
          <mesh castShadow receiveShadow geometry={nodes.Disc_FR.geometry} material={materials.Material_Disc_Static} position={[0.01, 0.133, 0.005]} rotation={[Math.PI, -0.035, Math.PI]} scale={[1.039, 0.891, 0.891]} />
          <mesh castShadow receiveShadow geometry={nodes.Hub_FR.geometry} material={materials.Material_Structure_Lucid_Static} position={[-0.647, 0.029, 0.004]} scale={0.828} />
          <mesh castShadow receiveShadow geometry={nodes.Rim_Center_FR.geometry} material={materials.Material_Rim_Centerlock} position={[0.101, 0.01, 0]} />
          <mesh castShadow receiveShadow geometry={nodes.Rim_Outer_FR.geometry} material={materials.Material_Rim_Primary} position={[0.101, 0.01, 0]} />
          <mesh castShadow receiveShadow geometry={nodes.Tire_FR.geometry} material={materials.Material_Tire_Static} position={[-0.01, 0.005, 0.006]} scale={[1.171, 0.961, 0.961]} />
        </group>
        <group position={[0.021, -0.012, -0.154]} rotation={[Math.PI / 2, -0.035, Math.PI]} scale={[1.254, 1.076, 1.076]}>
          <mesh castShadow receiveShadow geometry={nodes.Brake_Static_FR_1.geometry} material={materials.Material_Wheels_Bolts_Static} />
          <mesh castShadow receiveShadow geometry={nodes.Brake_Static_FR_2.geometry} material={materials.Material_Radiator_Static} />
        </group>
        <mesh castShadow receiveShadow geometry={nodes.Caliper_Paint_FR.geometry} material={materials.Material_Caliper_Dynamic} position={[0.021, -0.012, -0.154]} rotation={[Math.PI / 2, -0.035, Math.PI]} scale={[1.254, 1.076, 1.076]} />
      </group>
      <group position={[-0.769, 0.303, -1.293]}>
        <group position={[-0.007, 0.002, 0.009]} rotation={[-Math.PI / 2, -0.035, Math.PI]} scale={[-1.254, -1.076, -1.076]}>
          <mesh castShadow receiveShadow geometry={nodes.Disc_RL.geometry} material={materials.Material_Disc_Static} position={[-0.013, 0.147, -0.001]} />
          <mesh castShadow receiveShadow geometry={nodes.Hub_RL.geometry} material={materials.Material_Structure_Lucid_Static} position={[0.618, 0.019, 0.061]} rotation={[0, -0.036, -Math.PI]} scale={[-0.797, -0.929, -0.929]} />
          <mesh castShadow receiveShadow geometry={nodes.Rim_Center_RL.geometry} material={materials.Material_Rim_Centerlock} position={[-0.1, 0.008, 0.002]} rotation={[-Math.PI, 0.036, -Math.PI]} scale={[0.963, 1.122, 1.122]} />
          <mesh castShadow receiveShadow geometry={nodes.Rim_Outer_RL.geometry} material={materials.Material_Rim_Primary} position={[-0.1, 0.008, 0.002]} rotation={[-Math.PI, 0.036, -Math.PI]} scale={[0.963, 1.122, 1.122]} />
          <mesh castShadow receiveShadow geometry={nodes.Tire_RL.geometry} material={materials.Material_Tire_Static} position={[0.006, 0.003, 0]} rotation={[-Math.PI, 0.036, -Math.PI]} scale={[1.128, 1.079, 1.079]} />
        </group>
        <group position={[-0.024, 0.002, -0.149]} rotation={[-Math.PI / 2, -0.035, Math.PI]} scale={[-1.254, -1.076, -1.076]}>
          <mesh castShadow receiveShadow geometry={nodes.Brake_Static_RL_1.geometry} material={materials.Material_Radiator_Static} />
          <mesh castShadow receiveShadow geometry={nodes.Brake_Static_RL_2.geometry} material={materials.Material_Wheels_Bolts_Static} />
        </group>
        <mesh castShadow receiveShadow geometry={nodes.Caliper_Paint_RL.geometry} material={materials.Material_Caliper_Dynamic} position={[-0.024, 0.002, -0.149]} rotation={[-Math.PI / 2, -0.035, Math.PI]} scale={[-1.254, -1.076, -1.076]} />
      </group>
      <group position={[0.777, 0.298, -1.287]}>
        <group position={[-0.003, 0.001, -0.008]} rotation={[Math.PI / 2, -0.035, Math.PI]} scale={[1.254, 1.076, 1.076]}>
          <mesh castShadow receiveShadow geometry={nodes.Disc_RR.geometry} material={materials.Material_Disc_Static} position={[-0.016, 0.136, -0.005]} />
          <mesh castShadow receiveShadow geometry={nodes.Hub_RR.geometry} material={materials.Material_Structure_Lucid_Static} position={[0.615, 0.009, 0.057]} rotation={[-Math.PI, 0.036, -Math.PI]} scale={[0.797, 0.929, 0.929]} />
          <mesh castShadow receiveShadow geometry={nodes.Rim_Center_RR.geometry} material={materials.Material_Rim_Centerlock} position={[-0.103, -0.002, -0.002]} rotation={[-Math.PI, 0.036, -Math.PI]} scale={[0.963, 1.122, 1.122]} />
          <mesh castShadow receiveShadow geometry={nodes.Rim_Outer_RR.geometry} material={materials.Material_Rim_Primary} position={[-0.103, -0.002, -0.002]} rotation={[-Math.PI, 0.036, -Math.PI]} scale={[0.963, 1.122, 1.122]} />
          <mesh castShadow receiveShadow geometry={nodes.Tire_RR.geometry} material={materials.Material_Tire_Static} position={[0.003, -0.007, -0.004]} rotation={[-Math.PI, 0.036, -Math.PI]} scale={[1.128, 1.079, 1.079]} />
        </group>
        <group position={[0.017, 0.006, -0.155]} rotation={[Math.PI / 2, -0.035, Math.PI]} scale={[1.254, 1.076, 1.076]}>
          <mesh castShadow receiveShadow geometry={nodes.Brake_Static_RR_1.geometry} material={materials.Material_Wheels_Bolts_Static} />
          <mesh castShadow receiveShadow geometry={nodes.Brake_Static_RR_2.geometry} material={materials.Material_Radiator_Static} />
        </group>
        <mesh castShadow receiveShadow geometry={nodes.Caliper_Paint_RR.geometry} material={materials.Material_Caliper_Dynamic} position={[0.017, 0.006, -0.155]} rotation={[Math.PI / 2, -0.035, Math.PI]} scale={[1.254, 1.076, 1.076]} />
      </group>
      <group position={[0.819, 0.52, 0.575]}>
        <mesh castShadow receiveShadow geometry={nodes.Door_Accent_L.geometry} material={materials.Material_Interior_Stitching_Dynamic} position={[-0.143, 0.122, -0.542]} />
        <mesh castShadow receiveShadow geometry={nodes.Door_Glass_L.geometry} material={materials.Material_Glass_Cabin_Static} position={[-0.164, 0.51, -0.767]} />
        <group position={[-0.143, 0.122, -0.542]}>
          <mesh castShadow receiveShadow geometry={nodes.Door_Interior_Base_L_1.geometry} material={materials.Material_Interior_LightGrey_Plastic_Static} />
          <mesh castShadow receiveShadow geometry={nodes.Door_Interior_Base_L_2.geometry} material={materials.Material_Front_Speaker_Static} />
          <mesh castShadow receiveShadow geometry={nodes.Door_Interior_Base_L_3.geometry} material={materials.Material_Exterior_Badges_Dynamic} />
        </group>
        <mesh castShadow receiveShadow geometry={nodes.Door_Leather_Primary_L.geometry} material={materials.Material_Leather_Primary} position={[-0.143, 0.122, -0.542]} />
        <mesh castShadow receiveShadow geometry={nodes.Door_Leather_Secondary_L.geometry} material={materials.Material_Upper_Leather_Dynamic} position={[-0.143, 0.122, -0.542]} />
        <group position={[-0.143, 0.122, -0.542]}>
          <mesh castShadow receiveShadow geometry={nodes.Door_Metal_Trim_L_1.geometry} material={materials.Material_Interior_Metal_Static} />
          <mesh castShadow receiveShadow geometry={nodes.Door_Metal_Trim_L_2.geometry} material={materials.Material_Interior_Metal_Lucid_Static} />
          <mesh castShadow receiveShadow geometry={nodes.Door_Metal_Trim_L_3.geometry} material={materials.Material_Interior_Metal_Static} />
        </group>
        <mesh castShadow receiveShadow geometry={nodes.Door_Mirror_L.geometry} material={materials.Material_Mirror_Glass_Static} position={[0.092, 0.374, -0.325]} />
        <mesh castShadow receiveShadow geometry={nodes.Door_Paint_L.geometry} material={materials.Material_Chassis_Paint} position={[0.092, 0.374, -0.325]} />
        <mesh castShadow receiveShadow geometry={nodes.Door_Painted_Trim_L_Dynamic.geometry} material={materials.Material_Interior_Metal_Static} position={[-0.143, 0.122, -0.542]} />
        <group position={[0.092, 0.374, -0.325]}>
          <mesh castShadow receiveShadow geometry={nodes.Door_Plastic_L_1.geometry} material={materials.Material_RubberTrim_Static} />
          <mesh castShadow receiveShadow geometry={nodes.Door_Plastic_L_2.geometry} material={materials.Material_Carbon_Trim_Static} />
          <mesh castShadow receiveShadow geometry={nodes.Door_Plastic_L_3.geometry} material={materials.Material_Exterior_LowerAero_Dynamic} />
        </group>
      </group>
      <group position={[-0.826, 0.575, 0.565]}>
        <mesh castShadow receiveShadow geometry={nodes.Door_Accent_R.geometry} material={materials.Material_Interior_Stitching_Dynamic} position={[0.15, 0.071, -0.529]} />
        <mesh castShadow receiveShadow geometry={nodes.Door_Glass_R.geometry} material={materials.Material_Glass_Cabin_Static} position={[0.171, 0.455, -0.753]} />
        <group position={[0.15, 0.071, -0.529]}>
          <mesh castShadow receiveShadow geometry={nodes.Door_Interior_Base_R_1.geometry} material={materials.Material_Interior_LightGrey_Plastic_Static} />
          <mesh castShadow receiveShadow geometry={nodes.Door_Interior_Base_R_2.geometry} material={materials.Material_Front_Speaker_Static} />
          <mesh castShadow receiveShadow geometry={nodes.Door_Interior_Base_R_3.geometry} material={materials.Material_Exterior_Badges_Dynamic} />
        </group>
        <mesh castShadow receiveShadow geometry={nodes.Door_Leather_Primary_R.geometry} material={materials.Material_Leather_Primary} position={[0.15, 0.071, -0.529]} />
        <mesh castShadow receiveShadow geometry={nodes.Door_Leather_Secondary_R.geometry} material={materials.Material_Upper_Leather_Dynamic} position={[0.15, 0.071, -0.529]} />
        <group position={[0.15, 0.071, -0.529]}>
          <mesh castShadow receiveShadow geometry={nodes.Door_Metal_Trim_R_1.geometry} material={materials.Material_Interior_Metal_Lucid_Static} />
          <mesh castShadow receiveShadow geometry={nodes.Door_Metal_Trim_R_2.geometry} material={materials.Material_Interior_Metal_Static} />
        </group>
        <mesh castShadow receiveShadow geometry={nodes.Door_Mirror_R.geometry} material={materials.Material_Mirror_Glass_Static} position={[-0.085, 0.319, -0.315]} />
        <mesh castShadow receiveShadow geometry={nodes.Door_Paint_R.geometry} material={materials.Material_Chassis_Paint} position={[-0.085, 0.319, -0.315]} />
        <mesh castShadow receiveShadow geometry={nodes.Door_Painted_Trim_R_Dynamic.geometry} material={materials.Material_Interior_Metal_Static} position={[0.15, 0.071, -0.529]} />
        <group position={[0.089, 0.298, -0.677]}>
          <mesh castShadow receiveShadow geometry={nodes.Door_Plastic_R_1.geometry} material={materials.Material_RubberTrim_Static} />
          <mesh castShadow receiveShadow geometry={nodes.Door_Plastic_R_2.geometry} material={materials.Material_Carbon_Trim_Static} />
          <mesh castShadow receiveShadow geometry={nodes.Door_Plastic_R_3.geometry} material={materials.Material_Exterior_LowerAero_Dynamic} />
        </group>
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Aero_Engine_Fans_Carbon.geometry} material={materials.Material_Carbon_Trim_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Aero_Fender_Louvers.geometry} material={materials.Material_Exterior_LowerAero_Dynamic} />
      <mesh castShadow receiveShadow geometry={nodes.Aero_Front_Splitter.geometry} material={materials.Material_Exterior_LowerAero_Dynamic} />
      <mesh castShadow receiveShadow geometry={nodes.Aero_Rear_Diffuser.geometry} material={materials.Material_Exterior_LowerAero_Dynamic} />
      <mesh castShadow receiveShadow geometry={nodes.Aero_Roof_Panel.geometry} material={materials.Material_Exterior_Weissach_Dynamic} />
      <mesh castShadow receiveShadow geometry={nodes.Aero_Roof_Rails.geometry} material={materials.Material_Exterior_LowerAero_Dynamic} />
      <mesh castShadow receiveShadow geometry={nodes.Aero_Sideskirts.geometry} material={materials.Material_Exterior_LowerAero_Dynamic} />
      <mesh castShadow receiveShadow geometry={nodes.Aero_Tailgate.geometry} material={materials.Material_Exterior_LowerAero_Dynamic} />
      <mesh castShadow receiveShadow geometry={nodes.Aero_Wing_Supports.geometry} material={materials.Material_Exterior_LowerAero_Dynamic} />
      <mesh castShadow receiveShadow geometry={nodes.Badge_Rear_Lettering.geometry} material={materials.Material_Exterior_Badges_Dynamic} />
      <mesh castShadow receiveShadow geometry={nodes.Chassis_Paint.geometry} material={materials.Material_Chassis_Paint} />
      <mesh castShadow receiveShadow geometry={nodes.Windows_Cabin_Static.geometry} material={materials.Material_Glass_Cabin_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Wing_Endplates.geometry} material={materials.Material_Exterior_LowerAero_Dynamic} />
      <mesh castShadow receiveShadow geometry={nodes.Hood_Aero_Vents_Static.geometry} material={materials.Material_Exterior_LowerAero_Dynamic} />
      <mesh castShadow receiveShadow geometry={nodes.Hood_Badge_Logo.geometry} material={materials.Exterior_Badges} />
      <mesh castShadow receiveShadow geometry={nodes.Hood_Carbon_Center.geometry} material={materials.Material_Exterior_Weissach_Dynamic} />
      <mesh castShadow receiveShadow geometry={nodes.Hood_Paint.geometry} material={materials.Material_Chassis_Paint} />
      <mesh castShadow receiveShadow geometry={nodes.Hood_Radiator_Static.geometry} material={materials.Material_Radiator_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Headlight_Emissive.geometry} material={materials.Material_Headlight_Emissive} />
      <mesh castShadow receiveShadow geometry={nodes.HeadLight_Glass.geometry} material={materials.Material_Glass_Lights_Static} />
      <mesh castShadow receiveShadow geometry={nodes.HeadLight_Housing_Static.geometry} material={materials.Material_Plastic_Smooth_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Signal_Front_Emissive.geometry} material={materials.Material_Exterior_Badges_Dynamic} />
      <mesh castShadow receiveShadow geometry={nodes.Signal_Front_Glass.geometry} material={materials.Material_Glass_Lights_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Signal_Side_Emissive.geometry} material={materials.Material_Signal_Emissive} />
      <mesh castShadow receiveShadow geometry={nodes.Signal_Side_Glass.geometry} material={materials.Material_Glass_Lights_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Licence_Plate_Emissive.geometry} material={materials.Material_LicensePlateLight_Emissive} />
      <mesh castShadow receiveShadow geometry={nodes.License_Plate_Glass.geometry} material={materials.Material_Glass_Lights_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Rear_Reflactors_Red.geometry} material={materials.Material_Reflector_Red_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Tailgate_Brake_Emissive.geometry} material={materials.Material_Taillight_Brake_Emissive} />
      <mesh castShadow receiveShadow geometry={nodes.Tailgate_Glass.geometry} material={materials.Material_Glass_Cabin_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Taillight_Brake_Emissive.geometry} material={materials.Material_Taillight_Brake_Emissive} />
      <mesh castShadow receiveShadow geometry={nodes.Taillight_Housing_Static_AntiChrome.geometry} material={materials.Material_Taillight_Housing_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Taillight_Housing_Static_PlasticSmooth.geometry} material={materials.Material_Plastic_Smooth_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Taillight_Main_Glass.geometry} material={materials.Material_Glass_Lights_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Taillight_Strip_Emissive.geometry} material={materials.Material_Taillight_Emissive} />
      <mesh castShadow receiveShadow geometry={nodes.Wing_Flap_Active.geometry} material={materials.Material_Exterior_Weissach_Dynamic} />
      <mesh castShadow receiveShadow geometry={nodes.Chassis_Underbody_Static_1.geometry} material={materials.Material_Radiator_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Chassis_Underbody_Static_2.geometry} material={materials.Material_Structure_Lucid_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Chassis_Underbody_Static_3.geometry} material={materials.Material_Structure_Opaque_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Chassis_Window_Trims_Static_1.geometry} material={materials.Material_RubberTrim_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Chassis_Window_Trims_Static_2.geometry} material={materials.Material_RubberTrim2_Staitc} />
      <mesh castShadow receiveShadow geometry={nodes.Chassis_Window_Trims_Static_3.geometry} material={materials.Material_Glass_Black_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Chassis_Window_Trims_Static_4.geometry} material={materials.Material_Carbon_Trim_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Exterior_Badges_1.geometry} material={materials.Material_Exterior_Badges_Dynamic} />
      <mesh castShadow receiveShadow geometry={nodes.Exterior_Badges_2.geometry} material={materials.Material_Exterior_ExhaustTips_Dynamic} />
      <mesh castShadow receiveShadow geometry={nodes.Exterior_Badges_3.geometry} material={materials.Material_Glass_Lights_Static} />
      <group position={[0.343, 0.76, 0.165]}>
        <group position={[0.002, -0.009, 0.028]} rotation={[-2.793, 0, Math.PI]}>
          <mesh castShadow receiveShadow geometry={nodes.Interior_SteeringWheel_Buttons_Static_1.geometry} material={materials.Material_SteeringWheel_Icons_Static} />
          <mesh castShadow receiveShadow geometry={nodes.Interior_SteeringWheel_Buttons_Static_2.geometry} material={materials.Material_SteeringWheel_Buttons_Static} />
          <mesh castShadow receiveShadow geometry={nodes.Interior_SteeringWheel_Buttons_Static_3.geometry} material={materials.Material_Logo_Static} />
        </group>
        <mesh castShadow receiveShadow geometry={nodes.Interior_SteeringWheel_Grip.geometry} material={materials.Material_Wheel_Leather_Dynamic} position={[0.002, -0.009, 0.028]} rotation={[-2.793, 0, Math.PI]} />
        <mesh castShadow receiveShadow geometry={nodes.Interior_SteeringWheel_Stitching_Dynamic.geometry} material={materials.Material_Interior_Stitching_Dynamic} position={[0.002, -0.009, 0.028]} rotation={[-2.793, 0, Math.PI]} />
        <mesh castShadow receiveShadow geometry={nodes.Interior_SteeringWheel_Trim_Dynamic.geometry} material={materials.Material_Interior_Plastic_Static} position={[0.002, -0.009, 0.028]} rotation={[-2.793, 0, Math.PI]} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Interior_Clock_Dial_Dynamic.geometry} material={materials.Material_DashClock_Dynamic} />
      <mesh castShadow receiveShadow geometry={nodes.Interior_Dash_Lower_Primary.geometry} material={materials.Material_Leather_Primary} />
      <mesh castShadow receiveShadow geometry={nodes.Interior_Dash_Upper_Secondary.geometry} material={materials.Material_Upper_Leather_Dynamic} />
      <mesh castShadow receiveShadow geometry={nodes.Interior_Headliner.geometry} material={materials.Material_Interior_Headliner_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Interior_Mirror_Housing_Dynamic.geometry} material={materials.Material_Exterior_LowerAero_Dynamic} />
      <mesh castShadow receiveShadow geometry={nodes.Interior_Painted_Trims_Dynamic.geometry} material={materials.Material_Interior_Accent_Dynamic} />
      <mesh castShadow receiveShadow geometry={nodes.Interior_Pedals_Metal.geometry} material={materials.Material_Interior_Padel_Metal_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Interior_Pedals_Rubber.geometry} material={materials.Material_Interior_Metal_Black_Lucid_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Interior_Seatbelts_Dynamic.geometry} material={materials.Material_SeatBelt_Dynamic} />
      <mesh castShadow receiveShadow geometry={nodes.Interior_Shifter_Trim_Dynamic.geometry} material={materials.Material_Interior_Plastic_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Interior_Shifter_Upholstery.geometry} material={materials.Material_Interior_Plastic_Darker_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Interior_Stitching_Dynamic.geometry} material={materials.Material_Interior_Stitching_Dynamic} />
      <mesh castShadow receiveShadow geometry={nodes.Interior_Tacho_Dial_Dynamic.geometry} material={materials.Material_Sticker_Tacho_Dynamic} />
      <mesh castShadow receiveShadow geometry={nodes.Interior_Tacho_Needle.geometry} material={materials.Material_Interior_Metal_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Seats_Leather_Primary.geometry} material={materials.Material_Leather_Primary} />
      <mesh castShadow receiveShadow geometry={nodes.Seats_Leather_Secondary.geometry} material={materials.Material_Leather_Secondary} />
      <mesh castShadow receiveShadow geometry={nodes.Interior_Carbon_Trims_1.geometry} material={materials.Material_Carbon_Trim_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Interior_Carbon_Trims_2.geometry} material={materials.Material_Carbon_Trim_Lighter_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Interior_Carpet_Static_1.geometry} material={materials.Material_Interior_Structure_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Interior_Carpet_Static_2.geometry} material={materials.Material_Interior_Carpet_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Interior_Dash_Trim_Dynamic_1.geometry} material={materials.Material_Interior_Plastic_Darker_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Interior_Dash_Trim_Dynamic_2.geometry} material={materials.Material_Interior_Plastic_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Interior_Glass_Static_1.geometry} material={materials.Material_Interior_Structure_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Interior_Glass_Static_2.geometry} material={materials.Material_Mirror_Glass_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Interior_Glass_Static_3.geometry} material={materials.Material_Glass_Lights_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Interior_Metal_Accents_1.geometry} material={materials.Material_Interior_Metal_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Interior_Metal_Accents_2.geometry} material={materials.Material_Interior_Clock_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Interior_Metal_Accents_3.geometry} material={materials.Material_Interior_Vent_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Interior_Screens_Digital_1.geometry} material={materials.Material_Interior_Screen_Digital} />
      <mesh castShadow receiveShadow geometry={nodes.Interior_Screens_Digital_2.geometry} material={materials.Material_Interior_Screen_GPS_Digital} />
      <mesh castShadow receiveShadow geometry={nodes.Interior_Shifter_Base_Static_1.geometry} material={materials.Material_Interior_Plastic_Darker_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Interior_Shifter_Base_Static_2.geometry} material={materials.Material_Exterior_Badges_Dynamic} />
      <mesh castShadow receiveShadow geometry={nodes.Interior_SteeringColumn_Stalks_1.geometry} material={materials.Material_Interior_Plastic_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Interior_SteeringColumn_Stalks_2.geometry} material={materials.Material_Interior_Metal_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Interior_SteeringColumn_Stalks_3.geometry} material={materials.Material_Interior_Plastic_Darker_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Interior_Tub_Static_1.geometry} material={materials.Material_Interior_Metal_Black_Lucid_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Interior_Tub_Static_2.geometry} material={materials.Material_Interior_Plastic_Lucid_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Interior_Tub_Static_3.geometry} material={materials.Material_Carbon_Trim_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Interior_Tub_Static_4.geometry} material={materials.Material_Warning_Triangle_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Interior_Tub_Static_5.geometry} material={materials.Material_Speakers_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Interior_Tub_Static_6.geometry} material={materials.Material_Behind_Vents_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Interior_Tub_Static_7.geometry} material={materials.Material_Interior_Plastic_Darker_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Interior_Tub_Static_8.geometry} material={materials.Material_Interior_Metallic_Structure_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Seats_Metal_Mechanics.geometry} material={materials.Material_Slide_Seat_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Seats_Metal_Mechanics_1.geometry} material={materials.Material_Interior_Metal_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Seats_Metal_Mechanics_2.geometry} material={materials.Material_SeatBelt_Buckle_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Seats_Metal_Mechanics_3.geometry} material={materials.Material_SeatBelt_Release_Button_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Seats_Metal_Mechanics_4.geometry} material={materials.Material_Buckle_Housing_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Seats_Metal_Mechanics_5.geometry} material={materials.Material_Seat_Plastic_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Exterior_ExhaustTips_Dynamic.geometry} material={materials.Material_Exterior_ExhaustTips_Dynamic} />
      <mesh castShadow receiveShadow geometry={nodes.Chassis_Powertrain_Static_1.geometry} material={materials.Material_Structure_Lucid_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Chassis_Powertrain_Static_2.geometry} material={materials.Material_Interior_Plastic_Darker_Static} />
      <mesh castShadow receiveShadow geometry={nodes.Chassis_Suspension_Static.geometry} material={materials.Material_Structure_Lucid_Static} />
    </group>
  )
}

useGLTF.preload('/models/gt3rs/scene-opt.glb')
