import type { VehicleConfig } from '../types';

export const gt3rsConfig: VehicleConfig = {
  id: 'gt3rs',
  modelPath: '/models/gt3rs/scene.glb',
  paintOptions: [

    // --- STANDARD ---
    { name: 'Guards Red', hex: '#d32f2f', finish: 'solid', category: 'standard' },
    { name: 'Shark Blue', hex: '#0277bd', finish: 'solid', category: 'standard' },
    { name: 'White', hex: '#f0f0f0', finish: 'solid', category: 'standard' },
    { name: 'Black', hex: '#0a0a0a', finish: 'solid', category: 'standard' },
    { name: 'Racing Yellow', hex: '#f7d117', finish: 'solid', category: 'standard' },

    // --- Metallic ---
    { name: 'Jet Black Metallic', hex: '#111111', finish: 'metallic', category: 'standard' },
    { name: 'GT Silver Metallic', hex: '#888C8D', finish: 'metallic', category: 'standard' },
    { name: 'Agate Grey Metallic', hex: '#595B5A', finish: 'metallic', category: 'standard' },
    { name: 'Oak Green Neo', hex: '#2B5331', finish: 'metallic', category: 'standard' },
    { name: 'Gentian Blue', hex: '#1C3683', finish: 'metallic', category: 'standard' },

    // --- SPECIAL ---
    { name: 'Python Green Chromaflair', hex: '#f0f00b', finish: 'special', category: 'standard' },

    // --- EXCLUSIVE MANUFAKTUR (PAINT TO SAMPLE - PTS) ---

    // Greens & Olives
    { name: 'Viridian Snow Metallic', hex: '#1B3B32', finish: 'metallic', category: 'pts' },
    { name: 'Mint Green', hex: '#47A883', finish: 'solid', category: 'pts' },
    { name: 'Lighter Green', hex: '#8AB85E', finish: 'solid', category: 'pts' },
    { name: 'Acid Green', hex: '#87D30F', finish: 'solid', category: 'pts' },
    { name: 'Light Green', hex: '#7FA943', finish: 'solid', category: 'pts' },
    { name: 'Peridot Metallic', hex: '#8B8B3B', finish: 'metallic', category: 'pts' },
    { name: 'Linden Green', hex: '#A3C159', finish: 'solid', category: 'pts' },
    { name: 'Green Yellow', hex: '#9ACD32', finish: 'solid', category: 'pts' },
    { name: 'Lizard Green', hex: '#77A32E', finish: 'solid', category: 'pts' },
    { name: 'Green', hex: '#1E4D2B', finish: 'solid', category: 'pts' },
    { name: 'Signal Green', hex: '#2CA05A', finish: 'solid', category: 'pts' },
    { name: 'Pure Green', hex: '#008B45', finish: 'solid', category: 'pts' },
    { name: 'Viper Green', hex: '#008443', finish: 'solid', category: 'pts' },
    { name: 'Python Green', hex: '#3A5F3C', finish: 'metallic', category: 'pts' },
    { name: 'Eberle Green', hex: '#2D4F3C', finish: 'solid', category: 'pts' },
    { name: 'Essmann Green', hex: '#005C39', finish: 'solid', category: 'pts' },
    { name: 'Willow Green', hex: '#797C5E', finish: 'solid', category: 'pts' },
    { name: 'Ashley Green', hex: '#2C4A3E', finish: 'solid', category: 'pts' },
    { name: 'Olive Green', hex: '#394025', finish: 'solid', category: 'pts' },
    { name: 'Auratium Green', hex: '#B5A642', finish: 'solid', category: 'pts' },
    { name: 'Smyrna Green', hex: '#4A8068', finish: 'solid', category: 'pts' },
    { name: 'Audrain Green Metallic', hex: '#2C3A32', finish: 'metallic', category: 'pts' },
    { name: 'British Racing Green', hex: '#004225', finish: 'solid', category: 'pts' },
    { name: 'Irish Green', hex: '#194A2D', finish: 'solid', category: 'pts' },
    { name: 'Verde Ermes Metallic', hex: '#2D3B2D', finish: 'metallic', category: 'pts' },
    { name: 'Malachite Green Metallic', hex: '#1A3B32', finish: 'metallic', category: 'pts' },
    { name: 'Graphite Green Metallic', hex: '#414A42', finish: 'metallic', category: 'pts' },
    { name: 'Nato Olive', hex: '#4F4F3B', finish: 'solid', category: 'pts' },
    { name: 'Felsen Green Metallic', hex: '#4A5348', finish: 'metallic', category: 'pts' },
    { name: 'Aventurine Green Metallic', hex: '#535A53', finish: 'metallic', category: 'pts' },
    { name: 'Black Olive', hex: '#38362D', finish: 'solid', category: 'pts' },
    { name: 'Oak Green Metallic', hex: '#3A4B38', finish: 'metallic', category: 'pts' },
    { name: 'Quercus Verde', hex: '#2A382B', finish: 'solid', category: 'pts' },
    { name: 'Underberg Green', hex: '#2C3A24', finish: 'solid', category: 'pts' },
    { name: 'Brewster Green', hex: '#1B2A21', finish: 'solid', category: 'pts' },
    { name: 'Verde British Racing Green', hex: '#003B21', finish: 'solid', category: 'pts' },
    { name: 'Forest Green Metallic', hex: '#1E2C22', finish: 'metallic', category: 'pts' },
    { name: 'Fjord Green', hex: '#4A6055', finish: 'solid', category: 'pts' },
    { name: 'Amazonas Green Metallic', hex: '#233830', finish: 'metallic', category: 'pts' },
    { name: 'Arlo Green Metallic', hex: '#34463C', finish: 'metallic', category: 'pts' },
    { name: 'Porsche Racing Green Metallic', hex: '#1B2F28', finish: 'metallic', category: 'pts' },
    { name: 'Jet Green Metallic', hex: '#23322A', finish: 'metallic', category: 'pts' },
    { name: 'Verde Zeltweg Metallic', hex: '#1F2E26', finish: 'metallic', category: 'pts' },
    { name: 'Dark Olive Metallic', hex: '#353830', finish: 'metallic', category: 'pts' },

    // Yellows, Oranges & Golds
    { name: 'Speed Yellow', hex: '#F0D722', finish: 'solid', category: 'pts' },
    { name: 'Soler Yellow Metallic', hex: '#E6C65A', finish: 'metallic', category: 'pts' },
    { name: 'Atacama Yellow', hex: '#E6C229', finish: 'solid', category: 'pts' },
    { name: 'Signal Yellow', hex: '#F2A900', finish: 'solid', category: 'pts' },
    { name: 'Bahama Yellow', hex: '#E29F1D', finish: 'solid', category: 'pts' },
    { name: 'Nordic Gold Metallic', hex: '#C27C21', finish: 'metallic', category: 'pts' },
    { name: 'Sean Peach', hex: '#F4A460', finish: 'solid', category: 'pts' },
    { name: 'Signal Orange', hex: '#E5511B', finish: 'solid', category: 'pts' },
    { name: 'Pastel Orange', hex: '#F87A17', finish: 'solid', category: 'pts' },
    { name: 'Gulf Orange', hex: '#F05E16', finish: 'solid', category: 'pts' },
    { name: 'Cadmium Orange', hex: '#D9531E', finish: 'solid', category: 'pts' },
    { name: 'Lava Orange', hex: '#FF5B00', finish: 'solid', category: 'pts' },

    // Reds & Pinks
    { name: 'Nantucket Red', hex: '#B24C45', finish: 'solid', category: 'pts' },
    { name: 'Rose Red', hex: '#C43C55', finish: 'solid', category: 'pts' },
    { name: 'Peru Red', hex: '#8B2323', finish: 'solid', category: 'pts' },
    { name: 'GTS Red', hex: '#9C151C', finish: 'solid', category: 'pts' },
    { name: 'Superior Red Metallic', hex: '#7A1C24', finish: 'metallic', category: 'pts' },

    // Blues
    { name: '914 Olympic Blue', hex: '#4A709C', finish: 'solid', category: 'pts' },
    { name: 'Gulf Blue', hex: '#99C1D9', finish: 'solid', category: 'pts' },
    { name: 'Meissen Blue', hex: '#88A3B8', finish: 'solid', category: 'pts' },
    { name: 'Aetna Blue', hex: '#5A82A0', finish: 'solid', category: 'pts' },
    { name: 'Ipanema Blue Metallic', hex: '#3B627D', finish: 'metallic', category: 'pts' },
    { name: 'Miami Blue', hex: '#007A9B', finish: 'solid', category: 'pts' },
    { name: 'Riviera Blue', hex: '#2583BA', finish: 'solid', category: 'pts' },
    { name: 'Mexico Blue', hex: '#187BB0', finish: 'solid', category: 'pts' },
    { name: 'South Sea Blue Metallic', hex: '#2C5A78', finish: 'metallic', category: 'pts' },
    { name: 'Dani Blue', hex: '#1C4B78', finish: 'solid', category: 'pts' },
    { name: 'Shark Blue', hex: '#0277BD', finish: 'solid', category: 'pts' },
    { name: 'Voodoo Blue', hex: '#005BAA', finish: 'solid', category: 'pts' },
    { name: 'Arrow Blue', hex: '#103A71', finish: 'solid', category: 'pts' },
    { name: 'Maritime Blue', hex: '#1C4587', finish: 'solid', category: 'pts' },
    { name: 'Turquoise Blue', hex: '#007A87', finish: 'solid', category: 'pts' },
    { name: 'Nashy Blue', hex: '#1C5A87', finish: 'solid', category: 'pts' },
    { name: 'Oslo Blue', hex: '#295A76', finish: 'solid', category: 'pts' },
    { name: 'Club Blau', hex: '#0B3363', finish: 'solid', category: 'pts' },
    { name: 'Nogaro Blue Metallic', hex: '#1C3B6E', finish: 'metallic', category: 'pts' },
    { name: 'Golf Blue', hex: '#6B8EA8', finish: 'solid', category: 'pts' },
    { name: 'Azure Blue 356', hex: '#3A6080', finish: 'solid', category: 'pts' },
    { name: 'Yachting Blue Metallic', hex: '#324B5C', finish: 'metallic', category: 'pts' },
    { name: 'Manaus Blue', hex: '#1C3B52', finish: 'solid', category: 'pts' },
    { name: 'Jebsen Blue', hex: '#1C3A5C', finish: 'solid', category: 'pts' },
    { name: '944 Cobalt Blue Metallic', hex: '#182C52', finish: 'metallic', category: 'pts' },
    { name: 'Aqua Blue Metallic', hex: '#234A78', finish: 'metallic', category: 'pts' },
    { name: 'Albert Blue', hex: '#1C2E4A', finish: 'solid', category: 'pts' },
    { name: 'Bali Blue', hex: '#3A688C', finish: 'solid', category: 'pts' },
    { name: 'San Marino Blue Metallic', hex: '#193866', finish: 'metallic', category: 'pts' },
    { name: 'Iris Blue Metallic', hex: '#233257', finish: 'metallic', category: 'pts' },
    { name: 'Dark Blue Metallic', hex: '#141C2E', finish: 'metallic', category: 'pts' },
    { name: 'Dark Sea Blue', hex: '#1E2B38', finish: 'solid', category: 'pts' },
    { name: 'Night Blue Metallic', hex: '#141829', finish: 'metallic', category: 'pts' },
    { name: 'X Blue', hex: '#1A2536', finish: 'solid', category: 'pts' },
    { name: 'Moonlight Blue Metallic', hex: '#1A2232', finish: 'metallic', category: 'pts' },
    { name: 'Ocean Blue Metallic', hex: '#1C324A', finish: 'metallic', category: 'pts' },
    { name: 'Dark Sapphire Metallic', hex: '#182236', finish: 'metallic', category: 'pts' },

    // Purples & Berries
    { name: 'Viola Metallic', hex: '#4A3B52', finish: 'metallic', category: 'pts' },
    { name: 'Amethyst Metallic', hex: '#5A3B5C', finish: 'metallic', category: 'pts' },
    { name: 'Aubergine', hex: '#3D2935', finish: 'solid', category: 'pts' },
    { name: 'Ultraviolet', hex: '#4B3B5C', finish: 'solid', category: 'pts' },
    { name: 'Viola Purple Metallic', hex: '#3E2B4A', finish: 'metallic', category: 'pts' },
    { name: 'Loretta Purple', hex: '#5C3B5A', finish: 'solid', category: 'pts' },
    { name: 'Ruby Star', hex: '#C83C55', finish: 'solid', category: 'pts' },
    { name: 'Frozen Berry Metallic', hex: '#B58A94', finish: 'metallic', category: 'pts' },

    // Silvers, Greys & Whites
    { name: 'Moon Gem', hex: '#C2B8A8', finish: 'metallic', category: 'pts' },
    { name: 'Centenaire Silver', hex: '#C0C2C5', finish: 'metallic', category: 'pts' },
    { name: 'Sport Classic Grey', hex: '#898D8E', finish: 'solid', category: 'pts' },
    { name: 'Dolomite Silver Metallic', hex: '#9FA3A6', finish: 'metallic', category: 'pts' },
    { name: 'Grigio Campovolo', hex: '#7E8182', finish: 'solid', category: 'pts' },
    { name: 'Dolphin Grey', hex: '#858883', finish: 'solid', category: 'pts' },
    { name: 'Fish Silver Grey Metallic', hex: '#7A8285', finish: 'metallic', category: 'pts' },
    { name: '964 Polar Silver Metallic', hex: '#A3ADB8', finish: 'metallic', category: 'pts' },
    { name: 'Crayon', hex: '#D1D1CF', finish: 'solid', category: 'pts' },
    { name: 'Mode Grey', hex: '#8E8F8B', finish: 'solid', category: 'pts' },
    { name: 'Geyser Grey Metallic', hex: '#B0B0A8', finish: 'metallic', category: 'pts' },
    { name: 'Beige Grey', hex: '#A8A39A', finish: 'solid', category: 'pts' },
    { name: 'Stone Grey', hex: '#5A5F58', finish: 'solid', category: 'pts' },
    { name: 'Goodman Grey', hex: '#6B6E6F', finish: 'solid', category: 'pts' },
    { name: 'Nardo Grey', hex: '#686A6C', finish: 'solid', category: 'pts' },
    { name: 'Stone Grey Metallic', hex: '#5A5F58', finish: 'metallic', category: 'pts' },
    { name: 'China Grey', hex: '#7A7C7D', finish: 'solid', category: 'pts' },
    { name: 'Meteor Grey Metallic', hex: '#545657', finish: 'metallic', category: 'pts' },
    { name: 'Slate Grey 7015', hex: '#464A49', finish: 'solid', category: 'pts' },
    { name: 'Arctic Grey', hex: '#969B9E', finish: 'solid', category: 'pts' },
    { name: 'Grigio Telesto Metallic', hex: '#4A4D4E', finish: 'metallic', category: 'pts' },
    { name: 'Dolomite Grey Metallic', hex: '#525658', finish: 'metallic', category: 'pts' },
    { name: 'Parliament Grey Metallic', hex: '#424749', finish: 'metallic', category: 'pts' },
    { name: 'Alex Grey', hex: '#5E6264', finish: 'solid', category: 'pts' },
    { name: 'Graphite Grey', hex: '#3B3D3D', finish: 'solid', category: 'pts' },
    { name: 'Grey Black', hex: '#313333', finish: 'solid', category: 'pts' },
    { name: 'Grigio Scuro', hex: '#3A3D3E', finish: 'solid', category: 'pts' },
    { name: 'Slate Grey 6601', hex: '#4D5355', finish: 'solid', category: 'pts' },
    { name: 'Grigio Granito Metallic', hex: '#3E4244', finish: 'metallic', category: 'pts' },
    { name: 'Volcano Grey Metallic', hex: '#36393B', finish: 'metallic', category: 'pts' },
    { name: 'Carbon Grey Metallic', hex: '#2E3133', finish: 'metallic', category: 'pts' },
    { name: 'Carbon Steel Grey Metallic', hex: '#2A2D2F', finish: 'metallic', category: 'pts' },

    // Blacks & Browns
    { name: 'Basalt Black Metallic', hex: '#18181A', finish: 'metallic', category: 'pts' },
    { name: 'Carbon Black Metallic', hex: '#141416', finish: 'metallic', category: 'pts' },
    { name: 'Coffee Black', hex: '#282422', finish: 'solid', category: 'pts' },
    { name: 'Diamond Black Metallic', hex: '#161618', finish: 'metallic', category: 'pts' },
    { name: 'Macadamia Metallic', hex: '#4B3621', finish: 'metallic', category: 'pts' },
    { name: 'Anthracite Brown Metallic', hex: '#3B322C', finish: 'metallic', category: 'pts' },
    { name: 'Chestnut Brown Metallic', hex: '#3D261C', finish: 'metallic', category: 'pts' },
    { name: 'Sepia Brown', hex: '#382D23', finish: 'solid', category: 'pts' },
    { name: 'Ivory', hex: '#E6E3CF', finish: 'solid', category: 'pts' },
    { name: 'Cream White', hex: '#E3DAC6', finish: 'solid', category: 'pts' },
    { name: 'Carrara White Metallic', hex: '#EBEBEB', finish: 'metallic', category: 'pts' }
  ],
  aeroOptions: [
    { id: 'standard', label: 'Standard (Painted Body Color)' },
    { id: 'weissach', label: 'Weissach Package (Twill Carbon)' },
    { id: 'weissach_forged', label: 'Weissach Package (Forged Carbon)' }
  ],
  wheelOption: [
    { id: 'silver', name: 'Standard Silver Alloy', hex: '#888C8D' },
    { id: 'gold', name: 'Satin Aurum', hex: '#7F6B46' }
  ],
  caliperOptions: [
    { id: 'red', name: 'Guards Red (Steel Brakes)', hex: '#d32f2f' },
    { id: 'yellow', name: 'Speed Yellow (PCCB)', hex: '#f0d722' },
    { id: 'green', name: 'Acid Green (Hybrid)', hex: '#87d30f' },
    { id: 'black', name: 'High Gloss Black', hex: '#111111' }
  ]
};